/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void task_1(void);
void task_2(void);
void task_3(void);
void task_4(void);

//stack calculation macros
#define TASK_STACK_SIZE    1024U
#define SCHED_STACK_SIZE   1024U

#define SRAM_START 		   0x20000000U
#define SRAM_END 		   (SRAM_START+(128*1024))

#define T1_STACK_START     SRAM_END
#define T1_STACK_END      ((T1_STACK_START)-(1024))
#define T2_STACK_START 	   T1_STACK_END
#define T2_STACK_END       ((T2_STACK_START)-(1024))
#define T3_STACK_START     T2_STACK_END
#define T3_STACK_END       ((T3_STACK_START)-(1024))
#define T4_STACK_START     T3_STACK_END
#define T4_STACK_END       ((T4_STACK_START)-(1024))



int main(void)
{

    /* Loop forever */
	for(;;);
}

//task definitions
void task_1(void)
{
	while(1)
	{
		printf("this is TASK1 \r\n");
	}
}
void task_2(void)
{
	while(1)
		{
		printf("this is TASK2 \r\n");

		}

}
void task_3(void)
{
	while(1)
		{
		printf("this is TASK3 \r\n");

		}
}
void task_4(void)
{
	while(1)
		{
		printf("this is TASK4 \r\n");

		}
}

