/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void task_1(void);
void task_2(void);
void task_3(void);
void task_4(void);

void systick_init(uint32_t delay);

//stack calculation macros
#define TASK_STACK_SIZE    1024U
#define SCHED_STACK_SIZE   1024U

#define SRAM_START 		   0x20000000U
#define SRAM_END 		   (SRAM_START+(128*1024))

#define T1_STACK_START     SRAM_END
#define T1_STACK_END      ((T1_STACK_START)-(1024))
#define T2_STACK_START 	   T1_STACK_END
#define T2_STACK_END       ((T2_STACK_START)-(1024))
#define T3_STACK_START     T2_STACK_END
#define T3_STACK_END       ((T3_STACK_START)-(1024))
#define T4_STACK_START     T3_STACK_END
#define T4_STACK_END       ((T4_STACK_START)-(1024))

//systick config
#define HSI_CLK 			16000000U
#define SYSTICK_FREQ		HSI_CLK




int main(void)
{

	//start scheduler
	systick_init(1000U);
    /* Loop forever */
	for(;;);
}

//task definitions
void task_1(void)
{
	while(1)
	{
		printf("this is TASK1 \r\n");
	}
}
void task_2(void)
{
	while(1)
		{
		printf("this is TASK2 \r\n");

		}

}
void task_3(void)
{
	while(1)
		{
		printf("this is TASK3 \r\n");

		}
}
void task_4(void)
{
	while(1)
		{
		printf("this is TASK4 \r\n");

		}
}

//configure and enable SYSTICK TIMER
void systick_init(uint32_t delay_freq){

	//1. calculate reload value
	uint32_t count_val= SYSTICK_FREQ/delay_freq;

	//LOAD COUNT VALUE IN RELOAD REGISTER
	uint32_t *SYST_RVR = (uint32_t *)0xE000E014U;
	*SYST_RVR &= ~(0xFFFFFF);
	*SYST_RVR |= (count_val-1);
	//clear CVR
	uint32_t *SYST_CVR =(uint32_t*)0xE000E018U;
	*SYST_CVR =0;

	//SYST_CSR settings
	uint32_t *SYST_CSR = (uint32_t *) 0xE000E010U;
	*SYST_CSR |=(0x1<<2);
	*SYST_CSR |=(0x1<<1);
	*SYST_CSR |=(0x1<<0);

}

void SysTick_Handler(void)
{
	printf("inside systick handler \r\n");
}
