/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void task_1(void);
void task_2(void);
void task_3(void);
void task_4(void);

void systick_init(uint32_t delay);
void scheduler_stackl_init(uint32_t stackstart);
void task_stack_init(void);
void switch_to_psp(void);
void enable_processor_faults(void);
uint32_t get_psp(void);
void update_current_task(void);
void save_psp(uint32_t pspval);

//stack calculation macros
#define TASK_STACK_SIZE    1024U
#define SCHED_STACK_SIZE   1024U

#define SRAM_START 		   0x20000000U
#define SRAM_END 		   (SRAM_START+(128*1024))

#define T1_STACK_START     SRAM_END
#define T1_STACK_END      ((T1_STACK_START)-(1024))
#define T2_STACK_START 	   T1_STACK_END
#define T2_STACK_END       ((T2_STACK_START)-(1024))
#define T3_STACK_START     T2_STACK_END
#define T3_STACK_END       ((T3_STACK_START)-(1024))
#define T4_STACK_START     T3_STACK_END
#define T4_STACK_END       ((T4_STACK_START)-(1024))
#define SCHEDULER_STACK_START T4_STACK_END


//systick config
#define HSI_CLK 			16000000U
#define SYSTICK_FREQ		HSI_CLK
//DUMMY SF
# define DUMMY_XPSR         0x01000000U
//PSP initialisation
uint32_t psp_of_task[4]={T1_STACK_START,T2_STACK_START, T3_STACK_START,T4_STACK_START};
uint32_t task_address[4]={(uint32_t)task_1,(uint32_t)task_2,(uint32_t)task_3,(uint32_t)task_4};
uint32_t current_task=0;
int main(void)
{

	enable_processor_faults();
	//initialise stack pointer of stack - mso give scgheduler starting address
	scheduler_stackl_init(SCHEDULER_STACK_START);

	//INITIALISE THE STACK OF TASKS
	task_stack_init();

	//start scheduler
	systick_init(1000U);
	//switch to psp before invoking task 1
	switch_to_psp();

	task_1(); //calling the first task
    /* Loop forever */
	for(;;);
}

//task definitions
void task_1(void)
{
	while(1)
	{
		printf("this is TASK1 \r\n");
	}
}
void task_2(void)
{
	while(1)
		{
		printf("this is TASK2 \r\n");

		}

}
void task_3(void)
{
	while(1)
		{
		printf("this is TASK3 \r\n");

		}
}
void task_4(void)
{
	while(1)
		{
		printf("this is TASK4 \r\n");

		}
}

//configure and enable SYSTICK TIMER
void systick_init(uint32_t delay_freq){

	//1. calculate reload value
	uint32_t count_val= SYSTICK_FREQ/delay_freq;

	//LOAD COUNT VALUE IN RELOAD REGISTER
	uint32_t *SYST_RVR = (uint32_t *)0xE000E014U;
	*SYST_RVR &= ~(0xFFFFFF);
	*SYST_RVR |= (count_val-1);
	//clear CVR
	uint32_t *SYST_CVR =(uint32_t*)0xE000E018U;
	*SYST_CVR =0;

	//SYST_CSR settings
	uint32_t *SYST_CSR = (uint32_t *) 0xE000E010U;
	*SYST_CSR |=(0x1<<2);
	*SYST_CSR |=(0x1<<1);
	*SYST_CSR |=(0x1<<0);

}


__attribute((naked))void scheduler_stackl_init(uint32_t stackstart){

	__asm volatile ("MSR MSP,R0 \n"
			"BX LR");

}
//=============================================================================================================
void task_stack_init(void)
{
	uint32_t * pPSP;
	for (int i=0;i<4;i++)
	{
		pPSP= (uint32_t *)psp_of_task[i];
		//xpsr initialise
		pPSP--;
		*pPSP=DUMMY_XPSR;

		pPSP--;
		*pPSP=task_address[i];

		pPSP--;
	    *pPSP=0xFFFFFFFD;

	    for (int j=0;j<13;j++)
	    {
			pPSP--;
		    *pPSP=0;
	    }

	    psp_of_task[i]=(uint32_t)pPSP;


	}


}

uint32_t get_psp(void)
{
	return psp_of_task[current_task];
}
void save_psp(uint32_t pspval)
{
	psp_of_task[current_task]=pspval;
}
void update_current_task(void)
{
	current_task++;
	current_task %= 4;
}

//=========================================================
__attribute__((naked)) void switch_to_psp(void)
{
	//initialise the psp and then change SPSEL bit
	 __asm volatile("PUSH {LR}");
	 __asm volatile("BL get_psp");
	 __asm volatile("MSR PSP,R0");
	 __asm volatile("POP {LR}");
	//CHANGE THE SPSEL BIT

	 __asm volatile("MOV R0,#0x02");
	 __asm volatile ("MSR CONTROL,R0");
	 __asm volatile("ISB");
	 __asm volatile ("BX LR");


}
//===========================================================
void enable_processor_faults(void)
{
	uint32_t*SHCSR = (uint32_t *) 0xE000ED24U;
	//enable faults
	*SHCSR |= (0x1<<18);
	*SHCSR |= (0x1<<17);
	*SHCSR |= (0x1<<16);

}
__attribute__((naked))void SysTick_Handler(void)
{

	//get the psp store the remaining context
	__asm volatile("MRS R0,PSP");
	__asm volatile("STMDB R0!, {R4-R11}");
	//save the psp value in psp_of_task[current task]
	__asm volatile("PUSH {LR}");
	__asm volatile("BL save_psp");
	//=======================================
	//RETRIEVING CONTEXT
	__asm volatile("BL update_current_task");
	__asm volatile("BL get_psp");

	__asm volatile("LDM R0!,{R4-R11}");

	__asm volatile("MSR PSP,R0");
	__asm volatile("POP {LR}");
	__asm volatile ("BX LR");

}
void MemManage_Handler(void)
{
	printf("inside MemManage handler \r\n");
	while(1);

}
void BusFault_Handler(void)
{
	printf("inside Busfault handler \r\n");
	while(1);

}
void UsageFault_Handler (void)
{
	printf("inside usagefault handler \r\n");
	while(1);

}
